rem $Header: svn://d02584/consolrepos/branches/AR.03.01/arc/1.0.0/install/sql/XXAR_RECEIPTS_RECORD_ID_S.sql 1706 2017-07-12 04:37:42Z svnuser $
CREATE SEQUENCE FMSMGR.XXAR_RECEIPTS_RECORD_ID_S START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE SYNONYM APPS.XXAR_RECEIPTS_RECORD_ID_S FOR FMSMGR.XXAR_RECEIPTS_RECORD_ID_S
/
