  --$Header :$
  
  CREATE TABLE FMSMGR.XXGL_COA_MAPPING_CONV_STG 
   (	RECORD_ID NUMBER, 
	SOURCE_CCID VARCHAR2(150), 
	SOURCE_ENTITY VARCHAR2(150), 
	SOURCE_SOURCE VARCHAR2(150), 
	SOURCE_COST_CENTRE VARCHAR2(150), 
	SOURCE_ACCOUNT VARCHAR2(150), 
	SOURCE_PROJECT VARCHAR2(150), 
	TARGET_CCID VARCHAR2(150), 
	TARGET_ORGANISATION VARCHAR2(150), 
	TARGET_ACCOUNT VARCHAR2(150), 
	TARGET_COST_CENTRE VARCHAR2(150), 
	TARGET_AUTHORITY VARCHAR2(150), 
	TARGET_PROJECT VARCHAR2(150), 
	TARGET_OUTPUT VARCHAR2(150), 
	TARGET_IDENTIFIER VARCHAR2(150), 
	STATUS VARCHAR2(60), 
	CREATED_BY NUMBER, 
	CREATION_DATE DATE, 
	LAST_UPDATED_BY NUMBER, 
	LAST_UPDATE_DATE DATE, 
	ERROR_MESSAGE VARCHAR2(2000)
   );
   
   CREATE SYNONYM XXGL_COA_MAPPING_CONV_STG FOR fmsmgr.XXGL_COA_MAPPING_CONV_STG;