package doi.oracle.apps.icx.por.rcv.server;
import oracle.apps.icx.por.rcv.server.ReceiveItemsVOImpl;
//import oracle.apps.icx.por.rcv.server.ReceiveReqItemsVOImpl;
//import oracle.apps.icx.por.rcv.server.ReceiveReqItemsVOImpl;
//  ---------------------------------------------------------------
//  --    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/* $Header: svn://d02584/consolrepos/branches/AR.03.02/poc/1.0.0/java/doi/oracle/apps/icx/por/rcv/server/DoiReceiveReqItemsVOImpl.java 1173 2017-06-23 00:56:04Z svnuser $ */
public class DoiReceiveReqItemsVOImpl extends ReceiveItemsVOImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public DoiReceiveReqItemsVOImpl()
  {
  }
}
