package doi.oracle.apps.icx.por.rcv.server;
import oracle.apps.icx.por.rcv.server.ReceiveItemsTxnVOImpl;
/* $Header: svn://d02584/consolrepos/branches/AP.00.02/poc/1.0.0/java/doi/oracle/apps/icx/por/rcv/server/DoiReceiveItemsTxnVOImpl.java 342 2017-05-09 00:40:24Z svnuser $ */
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class DoiReceiveItemsTxnVOImpl extends ReceiveItemsTxnVOImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public DoiReceiveItemsTxnVOImpl()
  {
  }
}
