package doi.oracle.apps.icx.por.req.server;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CMSLovAMImpl extends OAApplicationModuleImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public CMSLovAMImpl()
  {
  }

  /**
   * 
   * Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("doi.oracle.apps.icx.por.req.server", "CMSLovAMLocal");
  }

  /**
   * 
   * Container's getter for CMSLovVO
   */
  public CMSLovVOImpl getCMSLovVO()
  {
    return (CMSLovVOImpl)findViewObject("CMSLovVO");
  }
}