rem $Header: svn://d02584/consolrepos/branches/AR.02.03/arc/1.0.0/install/sql/XXAR_RECEIPTS_RECORD_ID_S.sql 323 2017-05-05 06:17:31Z sryan $
CREATE SEQUENCE FMSMGR.XXAR_RECEIPTS_RECORD_ID_S START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE SYNONYM APPS.XXAR_RECEIPTS_RECORD_ID_S FOR FMSMGR.XXAR_RECEIPTS_RECORD_ID_S
/
