--$Header :$

CREATE TABLE FMSMGR.XXGL_COA_DSDBI_CODE_COMB_STG 
   (	RECORD_ID NUMBER, 
        CODE_COMBINATION_ID NUMBER, 
        SEGMENT1 VARCHAR2(150), 
	SEGMENT2 VARCHAR2(150), 
	SEGMENT3 VARCHAR2(150), 
	SEGMENT4 VARCHAR2(150), 
	SEGMENT5 VARCHAR2(150), 
	ACCOUNT_TYPE VARCHAR2(150), 
	STATUS VARCHAR2(60), 
	CREATED_BY NUMBER, 
	CREATION_DATE DATE, 
	LAST_UPDATED_BY NUMBER, 
	LAST_UPDATE_DATE DATE, 
	RUN_ID NUMBER, 
	RUN_PHASE_ID NUMBER
   );
   
CREATE SYNONYM XXGL_COA_DSDBI_CODE_COMB_STG FOR fmsmgr.XXGL_COA_DSDBI_CODE_COMB_STG;   