package doi.oracle.apps.icx.por.rcv.server;
import oracle.apps.icx.por.rcv.server.ReceiveItemsVOImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class DoiReceivePurchaseItemsVOImpl extends ReceiveItemsVOImpl 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public DoiReceivePurchaseItemsVOImpl()
  {
  }
}