DECLARE
   l_sql  VARCHAR2(1000);
BEGIN
   l_sql := 'CREATE TABLE FMSMGR.XXGL_PAYROLL_DETAIL_TFM_BAK AS SELECT * FROM FMSMGR.XXGL_PAYROLL_DETAIL_TFM';
   EXECUTE IMMEDIATE l_sql;
   l_sql := 'CREATE TABLE FMSMGR.XXGL_PAYROLL_DETAIL_TMP_BAK AS SELECT * FROM FMSMGR.XXGL_PAYROLL_DETAIL_TMP';
   EXECUTE IMMEDIATE l_sql;
   l_sql := 'DROP TABLE FMSMGR.XXGL_PAYROLL_DETAIL_TFM';
   EXECUTE IMMEDIATE l_sql;
   l_sql := 'DROP TABLE FMSMGR.XXGL_PAYROLL_DETAIL_TMP';
   EXECUTE IMMEDIATE l_sql;
   l_sql := 'DROP SYNONYM XXGL_PAYROLL_DETAIL_TFM';
   EXECUTE IMMEDIATE l_sql;
   l_sql := 'DROP SYNONYM XXGL_PAYROLL_DETAIL_TMP';
   EXECUTE IMMEDIATE l_sql;
END;
/
