DECLARE
   l_sql  VARCHAR2(5000);
BEGIN
   l_sql := 'CREATE TABLE FMSMGR.XXAP_KOFAX_INV_STG_BAK AS SELECT * FROM FMSMGR.XXAP_KOFAX_INV_STG';
   EXECUTE IMMEDIATE l_sql;

   UPDATE XXAP_KOFAX_INV_STG
   SET    INVOICE_AMOUNT_EXC_GST = NULL, 
          GST_AMOUNT = NULL, 
          INVOICE_AMOUNT_INC_GST = NULL;
   COMMIT;

   l_sql := 'ALTER TABLE FMSMGR.XXAP_KOFAX_INV_STG MODIFY (INVOICE_AMOUNT_EXC_GST VARCHAR2(40), GST_AMOUNT ' ||
            'VARCHAR2(40), INVOICE_AMOUNT_INC_GST VARCHAR2(40))';
   EXECUTE IMMEDIATE l_sql;

   l_sql := 'UPDATE FMSMGR.XXAP_KOFAX_INV_STG b SET (INVOICE_AMOUNT_EXC_GST, GST_AMOUNT, INVOICE_AMOUNT_INC_GST) = ' ||
            '(SELECT INVOICE_AMOUNT_EXC_GST, GST_AMOUNT, INVOICE_AMOUNT_INC_GST ' ||
            'FROM FMSMGR.XXAP_KOFAX_INV_STG_BAK x ' ||
            'WHERE x.document_id = b.document_id)';
   EXECUTE IMMEDIATE l_sql;
   COMMIT;
END;
/
