rem $Header: svn://d02584/consolrepos/branches/AP.02.03/apc/1.0.0/install/sql/XXAP_INVOICES_RECORD_ID_S.sql 1027 2017-06-21 01:18:32Z svnuser $
CREATE SEQUENCE FMSMGR.XXAP_INVOICES_RECORD_ID_S START WITH 1 INCREMENT BY 1 NOCACHE
/
CREATE OR REPLACE SYNONYM APPS.XXAP_INVOICES_RECORD_ID_S FOR FMSMGR.XXAP_INVOICES_RECORD_ID_S
/
